# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fedpro/proto/federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fedpro/proto/federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x65\x64pro/proto/federated.proto\x12\tfederated\"!\n\x0cModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"?\n\rModelResponse\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t\"h\n\x10LocalModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\x12\x0f\n\x07weights\x18\x04 \x01(\x0c\x12\x0c\n\x04loss\x18\x05 \x01(\x02\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa6\x01\n\x11\x46\x65\x64\x65ratedLearning\x12\x45\n\x0eGetGlobalModel\x12\x17.federated.ModelRequest\x1a\x18.federated.ModelResponse\"\x00\x12J\n\x0eSendLocalModel\x12\x1b.federated.LocalModelUpdate\x1a\x19.federated.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedpro.proto.federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELREQUEST']._serialized_start=43
  _globals['_MODELREQUEST']._serialized_end=76
  _globals['_MODELRESPONSE']._serialized_start=78
  _globals['_MODELRESPONSE']._serialized_end=141
  _globals['_LOCALMODELUPDATE']._serialized_start=143
  _globals['_LOCALMODELUPDATE']._serialized_end=247
  _globals['_UPDATERESPONSE']._serialized_start=249
  _globals['_UPDATERESPONSE']._serialized_end=281
  _globals['_FEDERATEDLEARNING']._serialized_start=284
  _globals['_FEDERATEDLEARNING']._serialized_end=450
# @@protoc_insertion_point(module_scope)
